### ISSUE TITLE
Get Sounds

### ISSUE THREAD

**Issue by jharrilim** [pouladpld/bubble-gunner#6]
Sounds needed:
  - Lava falling
  - Bubble shooting
  - Bubble capturing animal
  - Animal starts falling
  - Lava popping bubble
  - Animal rescued
  - Animal died

Edit:
  - Button click

**Comment by pouladpld** [comment]
And also
- Main menu & Help scenes' bg

**Comment by pouladpld** [comment]
Bubble Pop

**Comment by poulad** [comment]
#### ToDo
- Bubble capturing animal
- Animal starts falling
- Animal died

#### DONE
-  Bubble shooting
-  Lava falling
- Button click
- Bubble pop
- Pterodactyl (to be played when it enters the scene)
- Volcano eruption. For the beginning of each level

**Comment by poulad** [comment]
@Kyle-Ainsley
